### ISSUE TITLE
adding up prompts

### ISSUE THREAD

**Issue by Saranmt** [Alvi-alvarez/sd-Img2img-batch-interrogator#2]
right now it adds up the interrogator prompt to the previous prompt, so if we have 10 images, the 10th one ends up with 11 prompts (Original prompt + 10 prompts from the 10 images) maybe there could be sort of an identifier added in so reset the prompt to the original one for each new image?

**Comment by Alvi-alvarez** [comment]
Fixed

**Comment by mflux** [comment]
Hi are you absolutely certain this is fixed? I am getting this issue in the latest version.
